services:
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}-traefik
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    healthcheck:
      retries: 3
      start_period: 20s
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
      timeout: 5s
    image: traefik:${TRAEFIK_VERSION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${COMPOSE_PROJECT_NAME}.${DNS_DOMAIN}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.router.loadbalancer.server.port=8080"
    networks:
      laravel:
        aliases:
          - "storage.${COMPOSE_PROJECT_NAME}.${DNS_DOMAIN}"
          - "rustfs.${COMPOSE_PROJECT_NAME}.${DNS_DOMAIN}"
    ports:
      - "${HTTP_FORWARD_PORT}:80"
      - "${HTTPS_FORWARD_PORT}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DIRECTORY}/traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DOCKER_DIRECTORY}/traefik/certs:/etc/traefik/certs:ro
