services:
  mysql:
    build:
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      DB_DATABASE_TESTING: ${COMPOSE_PROJECT_NAME}_testing
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_INITDB_SKIP_TZINFO: ${MYSQL_INITDB_SKIP_TZINFO:-1}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME}
    healthcheck:
      retries: 3
      start_period: 10s
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      timeout: 5s
    networks:
      - laravel
    ports:
      - "${DB_FORWARD_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ${DOCKER_DIRECTORY}/mysql/scripts/create-testing-database.sh:/docker-entrypoint-initdb.d/create-testing-database.sh

volumes:
  mysql-data:
    name: ${COMPOSE_PROJECT_NAME}-mysql-data
