services:
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    healthcheck:
      retries: 3
      start_period: 10s
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
    image: redis:${REDIS_VERSION}
    networks:
      - laravel
    ports:
      - "${REDIS_FORWARD_PORT}:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    name: ${COMPOSE_PROJECT_NAME}-redis-data

networks:
  laravel:
    external: true
    name: project.${COMPOSE_PROJECT_NAME}
